# Generated by Django 3.0.5 on 2020-04-20 08:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StuReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sDoa', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('sTime', models.CharField(max_length=10)),
                ('sDob', models.DateField()),
                ('sPhoto', models.ImageField(default='image', upload_to='')),
                ('sSetno', models.IntegerField()),
                ('sCourse', models.CharField(max_length=50)),
                ('sBranch', models.CharField(max_length=50)),
                ('sAttend', models.CharField(max_length=10)),
                ('sName', models.CharField(max_length=50)),
                ('sFather', models.CharField(max_length=50)),
                ('sGender', models.CharField(max_length=10)),
                ('sAddress', models.CharField(max_length=100)),
                ('sPhone1', models.CharField(max_length=10)),
                ('sPhone2', models.CharField(max_length=10)),
                ('sFee', models.IntegerField()),
                ('sQualifaction', models.CharField(max_length=50)),
                ('sComment', models.CharField(max_length=20)),
                ('sExam', models.CharField(max_length=20)),
            ],
        ),
    ]
